Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/urls.py
# Written by Christopher Breen for Sprint 1, last updated June 29, 2020 for Sprint 2
from django.urls import path

from . import views

app_name = 'sudoku'
urlpatterns = [
    path('', views.index, name='index'),
    path('howtoplay/', views.how_to_play, name='how_to_play'),
    path('newgame/', views.new_game, name='new_game'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('play/', views.play, name='play'),
    path('makegame/', views.make_game, name='make_game'),
    path('update_board/', views.update_board, name='update_board'),
    path('upload/', views.upload, name='upload'),
    path('uploadsuccess/', views.upload_success, name='upload_success'),
    path('get_hint/', views.get_hint, name='get_hint'),
    path('erase_obvious/', views.erase_obvious, name='erase_obvious'),
    path('load_puzzle/', views.load_puzzle, name='load_puzzle'),
    path('puzzleload/', views.puzzleload, name='puzzleload'),
    path('customgame/', views.custom_game, name='custom_game'),
    path('loadcustom/', views.load_custom, name='load_custom')
]

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku_proj/urls.py
# Written by Christopher Breen for Sprint 1, last updated June 23, 2020
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sudoku/', include('sudoku.urls')),
    path('accounts/login/', auth_views.LoginView.as_view())
]

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/models.py
# file: models.py
# author: Christopher Smith
# date: May 24, 2020

from django.db import models


# Puzzle table for storing pre-generated puzzles
class Puzzles(models.Model):
    puzzle_id = models.AutoField(primary_key=True)
    board = models.CharField(max_length=1863, unique=True)
    solution = models.CharField(max_length=1863)
    difficulty = models.CharField(max_length=1)
    naked_single = models.BooleanField(default=False)
    hidden_single = models.BooleanField(default=False)
    naked_pair = models.BooleanField(default=False)
    omission = models.BooleanField(default=False)
    naked_triplet = models.BooleanField(default=False)
    hidden_pair = models.BooleanField(default=False)
    naked_quad = models.BooleanField(default=False)
    hidden_triplet = models.BooleanField(default=False)
    hidden_quad = models.BooleanField(default=False)
    x_wing = models.BooleanField(default=False)
    swordfish = models.BooleanField(default=False)
    xy_wing = models.BooleanField(default=False)
    unique_rectangle = models.BooleanField(default=False)


# User table with stats for leaderboard determination
class Played(models.Model):
    played_id = models.AutoField(primary_key=True)
    puzzle_id = models.ForeignKey(Puzzles, on_delete=models.CASCADE)
    user = models.CharField(max_length=20)
    start_time = models.IntegerField(null=True)
    end_time = models.IntegerField(null=True)
    saved_board = models.CharField(max_length=1863)
    status = models.CharField(max_length=1)
    hints = models.IntegerField(default=0)

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/views.py
# file: views.py
# author: Christopher Breen
# last updated: July 7, 2020
import copy
import json
import re
import time

from django import forms
from django.contrib.admin.views.decorators import staff_member_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .create_game import custom_board
from .gamerecords import read_file, get_game, save_game, retrieve_puzzle
from .leaderboard import calculate_leaders
from .models import Puzzles
from .techniques import hidden_pair, naked_quad, hidden_triplet
from .techniques import hidden_quad, xwing, swordfish
from .techniques import naked_pair, omission, naked_triplet
from .techniques import naked_single, hidden_single
from .techniques import solvable_puzzle


def index(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    return render(request, 'sudoku/index.html')


def how_to_play(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    return render(request, 'sudoku/howtoplay.html')


def new_game(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    if 'board' in request.session:
        return render(request, 'sudoku/newgame.html', {
            'previous_board_in_mem': 'True'
        })
    else:
        return render(request, 'sudoku/newgame.html')


def puzzleload(request):
    # Written by Ben Brandhorst for Sprint 2, last updated July 4, 2020
    request.session['puzzleID'] = sanitized_puzzleid(request.POST['puzzleID'])
    return render(request, 'sudoku/puzzleload.html', )


def make_game(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    try:
        difficulty = sanitized_diff(request.POST['difficulty'])
        if not difficulty:
            return render(request, 'sudoku/newgame.html', {
                'error_message': 'Sorry, that difficulty level is not yet available.'
            })
        request.session['player'] = sanitized_player(request.POST['player_name'])
    except KeyError:
        return render(request, 'sudoku/newgame.html', {
            'error_message': 'Please select a difficulty level.'
        })
    else:
        # test code: replace new_board = and solution = with new_board, solution = for production
        # new_board = json.dumps(custom_board('63214597881??9???4?4??8??1????85????16?274??????96????481529?6?753416??9296738?4?'))
        # solution = json.dumps(custom_board('632145978817692534945387612324851796169274853578963421481529367753416289296738145'))
        new_board, solution = get_game(difficulty)
        request.session['orig_board'] = json.loads(new_board)
        request.session['board'] = json.loads(new_board)
        request.session['solution'] = json.loads(solution)
        request.session['start_time'] = round(time.time())
        if 'end_time' in request.session:
            del request.session['end_time']
        # W = Win, I = In-Progress, L = Lost, S = Surrendered
        request.session['status'] = 'I'
        request.session['hints'] = 0
        return HttpResponseRedirect(reverse('sudoku:play'))


def load_puzzle(request):
    # Written by Ben Brandhorst for Sprint 2, last updated July 3, 2020
    try:
        puzzleid = request.POST['puzzleID']
    except KeyError:
        return render(request, 'sudoku/leaderboard.html', {
            'error_message': 'Please select a puzzle to load.'
        })
    new_board, solution = retrieve_puzzle(puzzleid)
    request.session['player'] = sanitized_player(request.POST['player_name'])
    request.session['orig_board'] = json.loads(new_board)
    request.session['board'] = json.loads(new_board)
    request.session['solution'] = json.loads(solution)
    request.session['start_time'] = round(time.time())
    if 'end_time' in request.session:
        del request.session['end_time']
    # W = Win, I = In-Progress, L = Lost, S = Surrendered
    request.session['status'] = 'I'
    request.session['hints'] = 0
    return HttpResponseRedirect(reverse('sudoku:play'))


def sanitized_diff(diff):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    try:
        if 0 < int(diff) < 5:  # set upper bound to difficulty level not yet ready
            return str(diff)
        else:
            return False
    except ValueError:
        return False


def sanitized_player(player):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    regex = r"^[\w ]{4,20}$"
    match = re.fullmatch(regex, player)
    if match:
        return match[0]
    else:
        return 'Anonymous'


def sanitized_puzzleid(puzzleid):
    # Written by Ben Brandhorst for Sprint 2, last updated July 4, 2020
    regex = r"^[0-9]+$"
    match = re.fullmatch(regex, puzzleid)
    if match:
        return str(puzzleid)
    else:
        return False


def leaderboard(request):
    # Written by Christopher Smith and modified for Sprint 3
    diff1_record1 = calculate_leaders(1)[0]
    diff1_record2 = calculate_leaders(1)[1]
    diff1_record3 = calculate_leaders(1)[2]
    diff1_record4 = calculate_leaders(1)[3]
    diff1_record5 = calculate_leaders(1)[4]
    diff2_record1 = calculate_leaders(2)[0]
    diff2_record2 = calculate_leaders(2)[1]
    diff2_record3 = calculate_leaders(2)[2]
    diff2_record4 = calculate_leaders(2)[3]
    diff2_record5 = calculate_leaders(2)[4]
    diff3_record1 = calculate_leaders(3)[0]
    diff3_record2 = calculate_leaders(3)[1]
    diff3_record3 = calculate_leaders(3)[2]
    diff3_record4 = calculate_leaders(3)[3]
    diff3_record5 = calculate_leaders(3)[4]
    diff4_record1 = calculate_leaders(4)[0]
    diff4_record2 = calculate_leaders(4)[1]
    diff4_record3 = calculate_leaders(4)[2]
    diff4_record4 = calculate_leaders(4)[3]
    diff4_record5 = calculate_leaders(4)[4]
    return render(request, 'sudoku/leaderboard.html',
                  {'diff1_record1': diff1_record1,
                   'diff1_record2': diff1_record2,
                   'diff1_record3': diff1_record3,
                   'diff1_record4': diff1_record4,
                   'diff1_record5': diff1_record5,
                   'diff2_record1': diff2_record1,
                   'diff2_record2': diff2_record2,
                   'diff2_record3': diff2_record3,
                   'diff2_record4': diff2_record4,
                   'diff2_record5': diff2_record5,
                   'diff3_record1': diff3_record1,
                   'diff3_record2': diff3_record2,
                   'diff3_record3': diff3_record3,
                   'diff3_record4': diff3_record4,
                   'diff3_record5': diff3_record5,
                   'diff4_record1': diff4_record1,
                   'diff4_record2': diff4_record2,
                   'diff4_record3': diff4_record3,
                   'diff4_record4': diff4_record4,
                   'diff4_record5': diff4_record5})


def play(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    player = request.session.get('player')
    return render(request, 'sudoku/play.html', {'player': player})


def update_board(request):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    end_time = False

    # get JavaScript sessionStorage from POST
    updated_board = json.loads(request.POST.get('board'))
    if corrupted_board(updated_board):
        # user may have tampered with JavaScript Session Data
        return HttpResponse(status=400)

    start_time = json.loads(request.POST.get('start_time'))
    if not isinstance(start_time, int):
        return HttpResponse(status=400)

    status = request.POST.get('status')
    if status not in ['W', 'L', 'I', 'S']:
        return HttpResponse(status=400)

    try:
        hints = int(request.POST.get('hints'))
    except ValueError:
        return HttpResponse(status=400)

    if status == "W" and request.session['status'] != "W":
        # wasn't won before but it is now
        end_time = round(time.time())
        request.session['end_time'] = end_time
    elif status == "W" and request.session['status'] == "W":
        # already won, don't update end time
        end_time = request.session['end_time']

    # update Django Session
    request.session['board'] = updated_board
    request.session['start_time'] = start_time
    request.session['status'] = status
    request.session['hints'] = hints

    # update SQL3 Database: W = Win, I = In-Progress, L = Lost, S = Surrendered
    data = {'user': request.session['player'],
            'start_time': request.session['start_time'],
            'orig_board': request.session['orig_board'],
            'current_board': request.session['board'],
            'status': request.session['status'],
            'hints': request.session['hints']
            }
    if end_time:
        data.update({'end_time': end_time})

    # uncomment save_game when not using custom board for testing, comment when testing or save will crash
    save_game(data)
    return HttpResponse(status=204)


def corrupted_board(user_board):
    # Written by Christopher Breen for Sprint 1, last updated June 23, 2020
    # ensure user_board hasn't been tampered with
    try:
        if len(user_board) != 9:
            raise ValueError
        for row in user_board:
            if len(row) != 9:
                raise ValueError
            for col in row:
                if isinstance(col, list):
                    if not 0 < len(col) < 10:
                        raise ValueError
                    for candidates in col:
                        if not isinstance(candidates, int):
                            raise ValueError
                        elif not 0 < candidates < 10:
                            raise ValueError
                elif not isinstance(col, int):
                    raise ValueError
                elif not 0 < col < 10:

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/templates/sudoku/customgame.html
<!--
   Written by Christopher Breen for Sprint 3, last updated July 7th, 2020
   -->
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Create Custom Sudoku</title>
    <link rel="stylesheet" type="text/css" href="{%  static 'Materialize.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{%  static 'style.css' %}">
    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
</head>
<body>
<nav class="red darken-4" role="navigation">
    <div class="nav-wrapper">
        <a class="brand-logo right">Sudoku</a>
        <ul id="nav-mobile" class="align-left">
            <li><a href="{% url 'sudoku:index' %}">Home</a></li>
            <li><a href="{% url 'sudoku:how_to_play' %}">How to Play</a></li>
            <li><a href="{% url 'sudoku:new_game' %}">Play Game</a></li>
            <li><a href="{% url 'sudoku:leaderboard' %}">Leaderboard</a></li>
        </ul>
    </div>
</nav>
<main>

    <div class="container" id="new_game_form">

        <div class="row">
            <div class="card-panel blue-grey lighten-2">
                <h2 class="center-align">Custom Sudoku Puzzle</h2>
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form action="{% url 'sudoku:load_custom' %}" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <label for="player_name" class="black-text">Player Name:</label><br>
                        <input type="text" id="player_name" name="player_name"><br>
                    </div>
                    <div class="custompuzzle">
                        <label for="custompuzzle">Puzzle:</label><br>
                        <textarea id="custompuzzle" name="puzzle" cols="9" rows="9" maxlength="81"></textarea>
                    </div>
                    <p><input type="submit" value="Create Game"></p>
                </form>
                {% if previous_board_in_mem %}
                <button onclick="renderPlay()">Resume Previous</button>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        function renderPlay() {
            window.location.href = "{% url 'sudoku:play' %}";
        }
    </script>
    <script>
        // Source: https://codepen.io/gapcode/pen/vEJNZN
        // Get IE or Edge browser version
        var version = detectIE();

        if (version !== false && version < 12) {
            document.getElementById("new_game_form").style.display = "none";
            document.write('<h2 style="text-align: center">Internet Explorer is not supported.<br>Please upgrade to a modern browser.</h2>')
        }

        /**
         * detect IE
         * returns version of IE or false, if browser is not Internet Explorer
         */
        function detectIE() {
            var ua = window.navigator.userAgent;

            var msie = ua.indexOf('MSIE ');
            if (msie > 0) {
                // IE 10 or older => return version number
                return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
            }

            var trident = ua.indexOf('Trident/');
            if (trident > 0) {
                // IE 11 => return version number
                var rv = ua.indexOf('rv:');
                return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
            }

            var edge = ua.indexOf('Edge/');
            if (edge > 0) {
                // Edge (IE 12+) => return version number
                return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
            }

            // other browser
            return false;
        }
    </script>
</main>
<footer class="page-footer grey darken-3">
    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
    <div class="container">
        <h5 class="white-text">Developers</h5>
    </div>
    <div class="container">
        <div class="row">
            <div class="col s3">
                <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US"
                     data-type="horizontal" data-theme="dark" data-vanity="ben-brandhorst-8407911ab"><a
                        class="LI-simple-link"
                        href='https://www.linkedin.com/in/ben-brandhorst-8407911ab?trk=profile-badge'>Ben Brandhorst</a>
                </div>
            </div>
            <div class="col s1">
            </div>
            <div class="col s3">
                <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US"
                     data-type="horizontal" data-theme="dark" data-vanity="breencp"><a class="LI-simple-link"
                                                                                       href='https://www.linkedin.com/in/breencp?trk=profile-badge'>Christopher
                    Breen</a></div>
            </div>
            <div class="col s1">
            </div>
            <div class="col s3">
                <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US"
                     data-type="horizontal" data-theme="dark" data-vanity="christopher-smith-4791961b0"><a
                        class="LI-simple-link"
                        href='https://www.linkedin.com/in/christopher-smith-4791961b0?trk=profile-badge'>Christopher
                    Smith</a></div>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2020 Copyright Ben Brandhorst, Christopher Breen, and Christopher Smith
        </div>
    </div>
</footer>
</body>
</html>

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/templates/sudoku/newgame.html
<!--
   Written by Ben Brandhorst for Sprint 1, last updated July 9, 2020
   -->
<!DOCTYPE html>
<html lang="en">
   {% load static %}

   <head>
      <meta charset="UTF-8" />
      <title>Start New Sudoku Game</title>
      <link rel="stylesheet" type="text/css" href="{%  static 'Materialize.css' %}" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      <link rel="stylesheet" type="text/css" href="{%  static 'style.css' %}" />
      <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
   </head>

   <body>
      <nav class="red darken-4" role="navigation">
         <div class="nav-wrapper">
            <a class="brand-logo right">Sudoku</a>
            <ul id="nav-mobile" class="align-left">
               <li><a href="{% url 'sudoku:index' %}">Home</a></li>
               <li><a href="{% url 'sudoku:how_to_play' %}">How to Play</a></li>
               <li><a href="{% url 'sudoku:new_game' %}">Play Game</a></li>
               <li><a href="{% url 'sudoku:leaderboard' %}">Leaderboard</a></li>
            </ul>
         </div>
      </nav>
      <main>
         <div class="container" id="new_game_form">
            <div class="row">
               <div class="card-panel blue-grey lighten-2">
                  <h2 class="center-align">Create New Game</h2>
                  {% if error_message %}
                  <p><strong>{{ error_message }}</strong></p>
                  {% endif %}
                  <form action="{% url 'sudoku:make_game' %}" method="post">
                     <div class="input-field">
                        {% csrf_token %}
                        <label for="player_name" class="black-text">Player Name:</label><br />
                        <input type="text" id="player_name" name="player_name" /><br />
                     </div>
                     <br />
                     Difficulty Level:<br />
                     <p>
                        <input type="radio" id="disability" name="difficulty" value="1" />
                        <label for="disability" class="black-text">Easy</label>
                     </p>

                     <p>
                        <input type="radio" id="intelligent" name="difficulty" value="2" />
                        <label for="intelligent" class="black-text">Normal</label>
                     </p>

                     <p>
                        <input type="radio" id="bright" name="difficulty" value="3" />
                        <label for="bright" class="black-text">Hard</label>
                     </p>

                     <p>
                        <input type="radio" id="gifted" name="difficulty" value="4" />
                        <label for="gifted" class="black-text">Expert</label>
                     </p>

                     <p>
                        <button>Create Game</button>
                        <button type="button" onClick="createCustom()">Create Custom</button> {% if previous_board_in_mem %}
                        <button type="button" onclick="renderPlay()">Resume Previous</button> {% endif %}
                     </p>
                  </form>
               </div>
            </div>
         </div>
         <script>
            function renderPlay() {
               window.location.href = "{% url 'sudoku:play' %}";
            }

            function createCustom() {
               window.location.href = "{% url 'sudoku:custom_game' %}";
            }
         </script>
         <script>
            // Source: https://codepen.io/gapcode/pen/vEJNZN
            // Get IE or Edge browser version
            var version = detectIE();

            if (version !== false && version < 12) {
               document.getElementById("new_game_form").style.display = "none";
               document.write('<h2 style="text-align: center">Internet Explorer is not supported.<br>Please upgrade to a modern browser.</h2>');
            }

            /**
             * detect IE
             * returns version of IE or false, if browser is not Internet Explorer
             */
            function detectIE() {
               var ua = window.navigator.userAgent;

               var msie = ua.indexOf("MSIE ");
               if (msie > 0) {
                  // IE 10 or older => return version number
                  return parseInt(ua.substring(msie + 5, ua.indexOf(".", msie)), 10);
               }

               var trident = ua.indexOf("Trident/");
               if (trident > 0) {
                  // IE 11 => return version number
                  var rv = ua.indexOf("rv:");
                  return parseInt(ua.substring(rv + 3, ua.indexOf(".", rv)), 10);
               }

               var edge = ua.indexOf("Edge/");
               if (edge > 0) {
                  // Edge (IE 12+) => return version number
                  return parseInt(ua.substring(edge + 5, ua.indexOf(".", edge)), 10);
               }

               // other browser
               return false;
            }
         </script>
      </main>
      <footer class="page-footer grey darken-3">
         <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
         <div class="container">
            <h5 class="white-text">Developers</h5>
         </div>
         <div class="container">
            <div class="row">
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="ben-brandhorst-8407911ab">
                     <a class="LI-simple-link" href="https://www.linkedin.com/in/ben-brandhorst-8407911ab?trk=profile-badge">Ben Brandhorst</a>
                  </div>
               </div>
               <div class="col s1"></div>
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="breencp">
                     <a class="LI-simple-link" href="https://www.linkedin.com/in/breencp?trk=profile-badge">Christopher Breen</a>
                  </div>
               </div>
               <div class="col s1"></div>
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="christopher-smith-4791961b0">
                     <a class="LI-simple-link" href="https://www.linkedin.com/in/christopher-smith-4791961b0?trk=profile-badge">Christopher Smith</a>
                  </div>
               </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="container">
               © 2020 Copyright Ben Brandhorst, Christopher Breen, and Christopher Smith
            </div>
         </div>
      </footer>
   </body>
</html>

Trends Projects Comp Science/Group 7 Sudoku Codebase v1.0 (1)/sudoku/templates/sudoku/puzzleload.html
<!--
   Written by Ben Brandhorst for Sprint 2, last updated July 4, 2020
   -->
<!DOCTYPE html>
<html lang="en">
   {% load static %}
   <head>
      <meta charset="UTF-8">
      <title>UMGC CMSC495 Sudoku Project</title>
      <link rel="stylesheet" type="text/css" href="{%  static 'Materialize.css' %}">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="{%  static 'style.css' %}">
      <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
   </head>
   <body onload ="fillForm()">
      <main>
         <nav class="red darken-4" role="navigation">
            <div class="nav-wrapper">
               <a class="brand-logo right">Sudoku</a>
               <ul id="nav-mobile" class="align-left">
                  <li> <a href="{% url 'sudoku:index' %}">Home</a></li>
                  <li><a href="{% url 'sudoku:how_to_play' %}">How to Play</a></li>
                  <li><a href="{% url 'sudoku:new_game' %}">Play Game</a></li>
                  <li><a href="{% url 'sudoku:leaderboard' %}">Leaderboard</a></li>
               </ul>
            </div>
         </nav>
         <div class="container" id="load_puzzle_form">
            <div class="row">
               <h2 class="center-align">Load Puzzle</h2>
               {% if error_message %}
               <p><strong>{{ error_message }}</strong></p>
               {% endif %}
               <form action="{% url 'sudoku:load_puzzle' %}" method="post">
                  {% csrf_token %}
                  <div class="input-field">
                     <label for="player_name" class="black-text">Player Name:</label><br>
                     <input type="text" id="player_name" name="player_name"><br>
                  </div>
                  <p>
                  <div class="input-field">
                     <label for="puzzleID" class="black-text">Puzzle ID:</label><br>
                     <input type="text" id="puzzleID" name="puzzleID"
                        readonly><br>
                  </div>
                  <br><input type="submit" value="Load Puzzle">
               </form>
            </div>
         </div>

<script>
   function fillForm(){
      var puz = "{{ request.session.puzzleID}}";
      var inputText = document.getElementById("puzzleID");
      inputText.setAttribute('value', puz);}
</script>

      </main>
      <footer class="page-footer grey darken-3">
         <div class="container">
            <h5 class="white-text left-align">Developers</h5>
         </div>
         <div class="container">
            <div class="row">
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="ben-brandhorst-8407911ab"><a class="LI-simple-link" href='https://www.linkedin.com/in/ben-brandhorst-8407911ab?trk=profile-badge'>Ben Brandhorst</a></div>
               </div>
               <div class="col s1">
               </div>
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="breencp"><a class="LI-simple-link" href='https://www.linkedin.com/in/breencp?trk=profile-badge'>Christopher Breen</a></div>
               </div>
               <div class="col s1">
               </div>
               <div class="col s3">
                  <div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="christopher-smith-4791961b0"><a class="LI-simple-link" href='https://www.linkedin.com/in/christopher-smith-4791961b0?trk=profile-badge'>Christopher Smith</a></div>
               </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="container">
               © 2020 Copyright Ben Brandhorst, Christopher Breen, and Christopher Smith
            </div>
         </div>
      </footer>
   </body>
</html>